version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t hello-world-app .
  post_build:
    commands:
      - echo "Build completed"
      - echo "Running the Docker container"
      - docker run -d -p 3000:3000 hello-world-app

artifacts:
  files:
    - '**/*'
